<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Naresh_E" failures="0" tests="3" name="org.rmg1.practice.CreditCustomerTC3" time="67.940" errors="1" timestamp="2022-09-16T13:40:40 IST" skipped="2">
  <testcase classname="org.rmg1.practice.CreditCustomerTC3" name="testcase1" time="22.912">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="org.rmg1.practice.CreditCustomerTC3" name="testcase1" time="22.446">
    <error message="Cannot invoke &quot;org.sdet40.ObjectRepository.CreditCustomerActoin.creditAction(java.util.Map, String)&quot; because &quot;this.creditCustomerActoin&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.sdet40.ObjectRepository.CreditCustomerActoin.creditAction(java.util.Map, String)" because "this.creditCustomerActoin" is null
at org.rmg1.practice.CreditCustomerTC3.testcase1(CreditCustomerTC3.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="org.rmg1.practice.CreditCustomerTC3" name="testcase1" time="22.582">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
</testsuite> <!-- org.rmg1.practice.CreditCustomerTC3 -->
